categories = [
'Active Life',
'Fitness & Instruction',
'Trainers',
'Gyms',
'Martial Arts',
'Yoga',
'Dance Studios',
'Pilates',
'Education',
'Nutritionists',
'Boot Camps',
'Meditation Centers',
'Swimming Lessons/Schools',
'Arts & Entertainment',
'Boxing',
'Self-defense Classes',
'Interval Training Gyms',
'Life Coach',
'Brazilian Jiu-jitsu',
'Taekwondo',
'Cardio Classes',
'Dance Schools',
'Golf Lessons',
'Performing Arts',
'Kickboxing',
'Karate',
'Barre Classes',
'Supernatural Readings',
'Health Coach',
'Circuit Training Gyms',
'Sports Clubs',
'Kids Activities',
'Golf',
'Muay Thai',
'Tai Chi',
'Summer Camps',
'Chinese Martial Arts',
'Fashion',
'Swimming Pools',
'Amateur Sports Teams',
'Tennis',
'Psychics',
'Golf Equipment',
'Gymnastics'
]